# Generated by Django 6.0 on 2026-07-31 08:15

import ckeditor_uploader.fields
import dioceseapp.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('prayer_request', models.TextField()),
                ('is_contacted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Designation name', max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Priest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('position', models.CharField(choices=[('priest', 'Priest'), ('retired_priest', 'Retired Priest'), ('seminary_student', 'Seminary Student')], default='priest', max_length=20)),
                ('home_parish', models.CharField(blank=True, max_length=200, null=True)),
                ('ordained_on', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('retired_on', models.DateField(blank=True, null=True, verbose_name='Retired (Vicar) On')),
                ('pastoral_experience', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Pastoral Experience')),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='priests/')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=dioceseapp.models.publication_image_path)),
                ('file', models.FileField(upload_to=dioceseapp.models.publication_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Spiritual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(help_text='Title of the spiritual category', max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Detailed content/description of the spiritual category', null=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the category title (auto-generated)', max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated')),
            ],
            options={
                'verbose_name': 'Spiritual Category',
                'verbose_name_plural': 'Spiritual Categories',
                'ordering': ['category_title'],
            },
        ),
        migrations.CreateModel(
            name='Officebearer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the office bearer', max_length=150)),
                ('image', models.ImageField(blank=True, help_text='Profile photo of the office bearer', null=True, upload_to='officebearers/')),
                ('phone', models.CharField(help_text='10-digit phone number', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must contain exactly 10 digits.', regex='^\\d{10}$')])),
                ('email', models.EmailField(blank=True, help_text='Email address (optional)', max_length=254, null=True)),
                ('district', models.CharField(blank=True, help_text='District (optional)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated')),
                ('designation', models.ForeignKey(blank=True, help_text='Designation/position of the office bearer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officebearers', to='dioceseapp.designation')),
            ],
            options={
                'verbose_name': 'Office Bearer',
                'verbose_name_plural': 'Office Bearers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='parishes/')),
                ('location', models.CharField(max_length=250)),
                ('map_url', models.URLField(blank=True, help_text='Paste the Google Maps share link for this parish.', null=True, verbose_name='Google Maps URL')),
                ('vicar_name', models.CharField(blank=True, help_text='Vicar name (used as fallback if no priest is selected)', max_length=150, null=True)),
                ('established_year', models.PositiveIntegerField()),
                ('district', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('trustee', models.CharField(blank=True, max_length=150, null=True)),
                ('secretary', models.CharField(blank=True, max_length=150, null=True)),
                ('number_of_families', models.PositiveIntegerField(default=0)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant_vicar', models.ForeignKey(blank=True, limit_choices_to={'position': 'priest'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_vicar_parishes', to='dioceseapp.priest')),
                ('vicar', models.ForeignKey(blank=True, limit_choices_to={'position': 'priest'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parishes', to='dioceseapp.priest')),
            ],
            options={
                'verbose_name': 'Parish',
                'verbose_name_plural': 'Parishes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Coordinator name', max_length=150)),
                ('district', models.CharField(help_text='Coordinator district', max_length=100)),
                ('phone', models.CharField(help_text='10 digit phone number', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated')),
                ('designation', models.ForeignKey(blank=True, help_text='Coordinator designation/position', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinators', to='dioceseapp.designation')),
                ('spiritual', models.ForeignKey(help_text='Spiritual category this coordinator belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='coordinators', to='dioceseapp.spiritual')),
            ],
            options={
                'verbose_name': 'Coordinator',
                'verbose_name_plural': 'Coordinators',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpiritualOfficeBearer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this office bearer was added to this category')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this association is currently active')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this association (optional)', null=True)),
                ('officebearer', models.ForeignKey(help_text='Office bearer', on_delete=django.db.models.deletion.CASCADE, related_name='officebearer_spirituals', to='dioceseapp.officebearer')),
                ('spiritual', models.ForeignKey(help_text='Spiritual category', on_delete=django.db.models.deletion.CASCADE, related_name='spiritual_officebearers', to='dioceseapp.spiritual')),
            ],
            options={
                'verbose_name': 'Spiritual Office Bearer',
                'verbose_name_plural': 'Spiritual Office Bearers',
                'ordering': ['spiritual', 'officebearer'],
                'unique_together': {('spiritual', 'officebearer')},
            },
        ),
        migrations.AddField(
            model_name='spiritual',
            name='officebearers',
            field=models.ManyToManyField(blank=True, help_text='Office bearers associated with this spiritual category', related_name='spiritual_categories', through='dioceseapp.SpiritualOfficeBearer', to='dioceseapp.officebearer'),
        ),
        migrations.CreateModel(
            name='Karunyasparsham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('about', 'About'), ('project', 'Project')], default='about', max_length=20)),
                ('about_title', models.CharField(blank=True, max_length=200, null=True)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='karunyasparsham/about/')),
                ('about_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('project_title', models.CharField(blank=True, max_length=200, null=True)),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='karunyasparsham/projects/')),
                ('project_description', models.TextField(blank=True, null=True)),
                ('project_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('project_location', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.CharField(choices=[('inactive', 'Inactive'), ('completed', 'Completed'), ('processing', 'Processing')], default='processing', max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='karunyasparsham_projects', to='dioceseapp.category')),
            ],
            options={
                'verbose_name_plural': 'Karunyasparsham',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='dioceseapp__slug_e7a526_idx'), models.Index(fields=['content_type'], name='dioceseapp__content_333f89_idx'), models.Index(fields=['category'], name='dioceseapp__categor_3bde89_idx'), models.Index(fields=['active'], name='dioceseapp__active_08da9d_idx')],
            },
        ),
    ]
