# Generated by Django 6.0 on 2026-07-27 08:49

import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('prayer_request', models.TextField()),
                ('is_contacted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Designation name', max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spiritual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(help_text='Title of the spiritual category', max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Detailed content/description of the spiritual category', null=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the category title (auto-generated)', max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated')),
            ],
            options={
                'verbose_name': 'Spiritual Category',
                'verbose_name_plural': 'Spiritual Categories',
                'ordering': ['category_title'],
            },
        ),
        migrations.AlterField(
            model_name='priest',
            name='position',
            field=models.CharField(choices=[('priest', 'Priest'), ('retired_priest', 'Retired Priest'), ('seminary_student', 'Seminary Student')], default='priest', max_length=20),
        ),
        migrations.RemoveField(
            model_name='priest',
            name='location',
        ),
        migrations.AddField(
            model_name='priest',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='priest',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='priest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='priest',
            name='home_parish',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='priest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='priests/'),
        ),
        migrations.AddField(
            model_name='priest',
            name='ordained_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='priest',
            name='pastoral_experience',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Pastoral Experience'),
        ),
        migrations.AddField(
            model_name='priest',
            name='retired_on',
            field=models.DateField(blank=True, null=True, verbose_name='Retired (Vicar) On'),
        ),
        migrations.AddField(
            model_name='priest',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='priest',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Officebearer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the office bearer', max_length=150)),
                ('image', models.ImageField(blank=True, help_text='Profile photo of the office bearer', null=True, upload_to='officebearers/')),
                ('phone', models.CharField(help_text='10-digit phone number', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must contain exactly 10 digits.', regex='^\\d{10}$')])),
                ('email', models.EmailField(blank=True, help_text='Email address (optional)', max_length=254, null=True)),
                ('district', models.CharField(blank=True, help_text='District (optional)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated')),
                ('designation', models.ForeignKey(blank=True, help_text='Designation/position of the office bearer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officebearers', to='dioceseapp.designation')),
            ],
            options={
                'verbose_name': 'Office Bearer',
                'verbose_name_plural': 'Office Bearers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='parishes/')),
                ('location', models.CharField(max_length=250)),
                ('map_url', models.URLField(blank=True, help_text='Paste the Google Maps share link for this parish.', null=True, verbose_name='Google Maps URL')),
                ('vicar_name', models.CharField(blank=True, help_text='Vicar name (used as fallback if no priest is selected)', max_length=150, null=True)),
                ('established_year', models.PositiveIntegerField()),
                ('district', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('trustee', models.CharField(blank=True, max_length=150, null=True)),
                ('secretary', models.CharField(blank=True, max_length=150, null=True)),
                ('number_of_families', models.PositiveIntegerField(default=0)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant_vicar', models.ForeignKey(blank=True, limit_choices_to={'position': 'priest'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_vicar_parishes', to='dioceseapp.priest')),
                ('vicar', models.ForeignKey(blank=True, limit_choices_to={'position': 'priest'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parishes', to='dioceseapp.priest')),
            ],
            options={
                'verbose_name': 'Parish',
                'verbose_name_plural': 'Parishes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpiritualCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Coordinator name', max_length=150)),
                ('designation', models.CharField(help_text='Coordinator designation', max_length=150)),
                ('district', models.CharField(help_text='Coordinator district', max_length=100)),
                ('phone', models.CharField(help_text='10 digit phone number', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spiritual', models.ForeignKey(help_text='Spiritual organisation', on_delete=django.db.models.deletion.CASCADE, related_name='coordinators', to='dioceseapp.spiritual')),
            ],
            options={
                'verbose_name': 'Spiritual Coordinator',
                'verbose_name_plural': 'Spiritual Coordinators',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpiritualOfficeBearer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this office bearer was added to this category')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this association is currently active')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this association (optional)', null=True)),
                ('officebearer', models.ForeignKey(help_text='Office bearer', on_delete=django.db.models.deletion.CASCADE, related_name='officebearer_spirituals', to='dioceseapp.officebearer')),
                ('spiritual', models.ForeignKey(help_text='Spiritual category', on_delete=django.db.models.deletion.CASCADE, related_name='spiritual_officebearers', to='dioceseapp.spiritual')),
            ],
            options={
                'verbose_name': 'Spiritual Office Bearer',
                'verbose_name_plural': 'Spiritual Office Bearers',
                'ordering': ['spiritual', 'officebearer'],
                'unique_together': {('spiritual', 'officebearer')},
            },
        ),
        migrations.AddField(
            model_name='spiritual',
            name='officebearers',
            field=models.ManyToManyField(blank=True, help_text='Office bearers associated with this spiritual category', related_name='spiritual_categories', through='dioceseapp.SpiritualOfficeBearer', to='dioceseapp.officebearer'),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
