# Generated by Django 6.0 on 2026-07-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priest',
            name='position',
            field=models.CharField(choices=[('vicar', 'Vicar'), ('retired_priest', 'Retired Priest'), ('student_priest', 'Student Priest')], default='vicar', max_length=20),
        ),
        migrations.RemoveField(
            model_name='priest',
            name='location',
        ),
        migrations.AddField(
            model_name='priest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='priest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='priests/'),
        ),
        migrations.AddField(
            model_name='priest',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='priest',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
