# Generated by Django 6.0 on 2026-08-01 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0002_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='video_title',
        ),
    ]
