# Generated by Django 6.0 on 2026-07-27 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0002_contact_designation_spiritual_alter_priest_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Coordinator name', max_length=150)),
                ('district', models.CharField(help_text='Coordinator district', max_length=100)),
                ('phone', models.CharField(help_text='10 digit phone number', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated')),
                ('designation', models.ForeignKey(blank=True, help_text='Coordinator designation/position', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinators', to='dioceseapp.designation')),
                ('spiritual', models.ForeignKey(help_text='Spiritual category this coordinator belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='coordinators', to='dioceseapp.spiritual')),
            ],
            options={
                'verbose_name': 'Coordinator',
                'verbose_name_plural': 'Coordinators',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='SpiritualCoordinator',
        ),
    ]
