# Generated by Django 6.0 on 2026-07-18 09:16

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0002_alter_priest_position_remove_priest_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='priest',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='priest',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='priest',
            name='home_parish',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='priest',
            name='ordained_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='priest',
            name='pastoral_church',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='priest',
            name='pastoral_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='priest',
            name='pastoral_from_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='priest',
            name='pastoral_to_year',
            field=models.CharField(blank=True, default='Present', max_length=10, null=True),
        ),
    ]
