# Generated by Django 6.0 on 2026-08-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0003_remove_gallery_video_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Gallery Item', 'verbose_name_plural': 'Gallery Items'},
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='order',
        ),
        migrations.AddField(
            model_name='gallery',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='gallery/videos/', verbose_name='Video File'),
        ),
    ]
