# Generated by Django 6.0 on 2026-07-18 10:34

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0003_priest_blood_group_priest_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='parishes/')),
                ('location', models.CharField(max_length=250)),
                ('vicar_name', models.CharField(max_length=150)),
                ('established_year', models.PositiveIntegerField()),
                ('district', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('trustee', models.CharField(blank=True, max_length=150, null=True)),
                ('number_of_families', models.PositiveIntegerField(default=0)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parish',
                'verbose_name_plural': 'Parishes',
                'ordering': ['name'],
            },
        ),
    ]
