# Generated by Django 6.0 on 2026-08-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0004_alter_gallery_options_remove_gallery_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='prayer_books/', verbose_name='Book Cover Image')),
                ('file', models.FileField(blank=True, null=True, upload_to='prayer_books/files/', verbose_name='File (PDF, Excel, Word)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Prayer Book',
                'verbose_name_plural': 'Prayer Books',
                'ordering': ['title'],
            },
        ),
    ]
