# Generated by Django 6.0 on 2026-07-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0004_parish'),
    ]

    operations = [
        migrations.AddField(
            model_name='parish',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='parish',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
