# Generated by Django 6.0 on 2026-07-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0005_parish_latitude_parish_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parish',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='parish',
            name='longitude',
        ),
        migrations.AddField(
            model_name='parish',
            name='map_url',
            field=models.URLField(blank=True, help_text='Paste the Google Maps share link for this parish.', null=True, verbose_name='Google Maps URL'),
        ),
    ]
