# Generated by Django 6.0 on 2026-08-03 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0005_prayerbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='KalpanaYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(default='Kalpana', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kalpana Year',
                'verbose_name_plural': 'Kalpana Years',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='KalpanaDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('document_number', models.CharField(blank=True, max_length=50, null=True)),
                ('document_type', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word Document'), ('excel', 'Excel Spreadsheet'), ('other', 'Other')], default='pdf', max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('ml', 'Malayalam'), ('both', 'Both')], default='en', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='kalpana_documents/')),
                ('file_url', models.URLField(blank=True, help_text='External URL if file is hosted elsewhere', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kalpana_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dioceseapp.kalpanayear')),
            ],
            options={
                'verbose_name': 'Kalpana Document',
                'verbose_name_plural': 'Kalpana Documents',
                'ordering': ['order', 'title'],
            },
        ),
    ]
