# Generated by Django 6.0 on 2026-08-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0006_kalpanayear_kalpanadocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kalpanadocument',
            name='document_number',
        ),
        migrations.RemoveField(
            model_name='kalpanadocument',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='kalpanadocument',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='kalpanadocument',
            name='language',
        ),
        migrations.AlterField(
            model_name='kalpanadocument',
            name='file',
            field=models.FileField(default=1, upload_to='kalpana_documents/'),
            preserve_default=False,
        ),
    ]
