# Generated by Django 6.0 on 2026-07-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0006_remove_parish_latitude_remove_parish_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parish',
            name='map_url',
            field=models.URLField(blank=True, help_text='Paste the Google Maps share link or embed URL for this parish.', null=True, verbose_name='Google Maps URL'),
        ),
    ]
