# Generated by Django 6.0 on 2026-08-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0007_remove_kalpanadocument_document_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kalpanayear',
            options={'ordering': ['-year', '-created_at'], 'verbose_name': 'Kalpana Year', 'verbose_name_plural': 'Kalpana Years'},
        ),
        migrations.RemoveField(
            model_name='kalpanadocument',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='kalpanayear',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='kalpanayear',
            name='year',
            field=models.CharField(max_length=20),
        ),
    ]
