# Generated by Django 6.0 on 2026-07-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0007_alter_parish_map_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parish',
            name='map_url',
            field=models.URLField(blank=True, help_text='Paste the Google Maps share link for this parish.', null=True, verbose_name='Google Maps URL'),
        ),
    ]
