# Generated by Django 6.0 on 2026-08-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0008_alter_kalpanayear_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kalpana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Kalpana No. 171 – 2026', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('descriptions', models.TextField(blank=True, help_text='Separate descriptions with new line')),
                ('file', models.FileField(blank=True, null=True, upload_to='kalpana_files/%Y/%m/')),
                ('file_name', models.CharField(blank=True, help_text='Display name for the file', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kalpana',
                'verbose_name_plural': 'Kalpana',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='KalpanaDocument',
        ),
        migrations.DeleteModel(
            name='KalpanaYear',
        ),
    ]
