# Generated by Django 6.0 on 2026-07-20 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0008_alter_parish_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='parish',
            name='vicar',
            field=models.ForeignKey(blank=True, help_text='Select the priest who is the vicar of this parish', limit_choices_to={'position': 'vicar'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parishes', to='dioceseapp.priest'),
        ),
        migrations.AlterField(
            model_name='parish',
            name='vicar_name',
            field=models.CharField(blank=True, help_text='Vicar name (used as fallback if no priest is selected)', max_length=150, null=True),
        ),
    ]
