# Generated by Django 6.0 on 2026-08-03 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0009_kalpana_delete_kalpanadocument_delete_kalpanayear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kalpana',
            name='file',
        ),
        migrations.RemoveField(
            model_name='kalpana',
            name='file_name',
        ),
        migrations.CreateModel(
            name='KalpanaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='kalpana_files/%Y/%m/')),
                ('file_name', models.CharField(blank=True, help_text='Display name for the file', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the file content')),
                ('file_type', models.CharField(blank=True, help_text='PDF, Word, Excel, Image, etc.', max_length=20)),
                ('file_size', models.CharField(blank=True, help_text='File size in KB/MB', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('kalpana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dioceseapp.kalpana')),
            ],
            options={
                'verbose_name': 'Kalpana File',
                'verbose_name_plural': 'Kalpana Files',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
