# Generated by Django 6.0 on 2026-08-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0010_remove_kalpana_file_remove_kalpana_file_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kalpana',
            name='descriptions',
        ),
        migrations.AlterField(
            model_name='kalpana',
            name='title',
            field=models.CharField(help_text='e.g., Kalpana 2026, Kalpana 2025', max_length=200),
        ),
        migrations.AlterField(
            model_name='kalpanafile',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this file'),
        ),
        migrations.AlterField(
            model_name='kalpanafile',
            name='file_size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='kalpanafile',
            name='file_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
