# Generated by Django 6.0 on 2026-07-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0010_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_contacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
