# Generated by Django 6.0 on 2026-07-22 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0011_contact_is_contacted_contact_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='parish',
            name='assistant_vicar',
            field=models.ForeignKey(blank=True, help_text='Select the Assistant Vicar of this parish', limit_choices_to={'position': 'assistant_vicar'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_parishes', to='dioceseapp.priest'),
        ),
    ]
