# Generated by Django 6.0 on 2026-07-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0012_parish_assistant_vicar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priest',
            name='position',
            field=models.CharField(choices=[('vicar', 'Vicar'), ('assistant_vicar', 'Assistant Vicar'), ('retired_priest', 'Retired Priest'), ('student_priest', 'Student Priest')], default='vicar', max_length=20),
        ),
    ]
