# Generated by Django 6.0 on 2026-08-04 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0012_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('church_account_manual', 'Church Account Manual'), ('constitution_1934', '1934 Constitution'), ('guidelines', 'Guidelines')], max_length=50, verbose_name='Document Type')),
                ('file', models.FileField(help_text='Upload PDF, Word, or Excel files', upload_to='downloads/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'xls', 'xlsx'])])),
            ],
            options={
                'verbose_name': 'Download',
                'verbose_name_plural': 'Downloads',
                'db_table': 'downloads',
                'ordering': ['document_type'],
            },
        ),
    ]
