# Generated by Django 6.0 on 2026-08-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0013_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='parish',
            name='facebook_id',
            field=models.CharField(blank=True, help_text='Facebook page ID or username (e.g., parishname or 123456789)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parish',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Full Facebook page URL (optional, will be auto-generated if ID is provided)', null=True),
        ),
        migrations.AddField(
            model_name='parish',
            name='instagram_id',
            field=models.CharField(blank=True, help_text='Instagram username without @ (e.g., parishname)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parish',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Full Instagram profile URL (optional, will be auto-generated if ID is provided)', null=True),
        ),
        migrations.AddField(
            model_name='parish',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number with country code (e.g., +1234567890)', max_length=20, null=True),
        ),
    ]
