# Generated by Django 6.0 on 2026-07-22 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0013_alter_priest_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parish',
            name='assistant_vicar',
            field=models.ForeignKey(blank=True, help_text='Select Assistant Vicar from Vicar list', limit_choices_to={'position': 'vicar'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_vicar_parishes', to='dioceseapp.priest'),
        ),
        migrations.AlterField(
            model_name='priest',
            name='position',
            field=models.CharField(choices=[('vicar', 'Vicar'), ('retired_priest', 'Retired Priest'), ('student_priest', 'Student Priest')], default='vicar', max_length=20),
        ),
    ]
