# Generated by Django 6.0 on 2026-07-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0014_alter_parish_assistant_vicar_alter_priest_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='priest',
            name='retired_on',
            field=models.DateField(blank=True, null=True, verbose_name='Retired (Vicar) On'),
        ),
    ]
