# Generated by Django 6.0 on 2026-08-06 09:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0014_parish_facebook_id_parish_facebook_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='spiritual',
        ),
        migrations.AddField(
            model_name='coordinator',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address (optional)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='image',
            field=models.ImageField(blank=True, help_text='Profile photo of the coordinator', null=True, upload_to='coordinators/'),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='phone',
            field=models.CharField(help_text='10-digit phone number', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must contain exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.CreateModel(
            name='SpiritualCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this coordinator was added to this category')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this association is currently active')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this association (optional)', null=True)),
                ('coordinator', models.ForeignKey(help_text='Coordinator', on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_spirituals', to='dioceseapp.coordinator')),
                ('spiritual', models.ForeignKey(help_text='Spiritual category', on_delete=django.db.models.deletion.CASCADE, related_name='spiritual_coordinators', to='dioceseapp.spiritual')),
            ],
            options={
                'verbose_name': 'Spiritual Coordinator',
                'verbose_name_plural': 'Spiritual Coordinators',
                'ordering': ['spiritual', 'coordinator'],
                'unique_together': {('spiritual', 'coordinator')},
            },
        ),
        migrations.AddField(
            model_name='spiritual',
            name='coordinators',
            field=models.ManyToManyField(blank=True, help_text='Coordinators associated with this spiritual category', related_name='spiritual_categories', through='dioceseapp.SpiritualCoordinator', to='dioceseapp.coordinator'),
        ),
    ]
