# Generated by Django 6.0 on 2026-07-23 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0015_priest_retired_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='parish',
            name='secretary',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='parish',
            name='assistant_vicar',
            field=models.ForeignKey(blank=True, help_text='Select Assistant Priest from Priest list', limit_choices_to={'position': 'vicar'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_vicar_parishes', to='dioceseapp.priest'),
        ),
        migrations.AlterField(
            model_name='priest',
            name='position',
            field=models.CharField(choices=[('priest', 'Priest'), ('retired_priest', 'Retired Priest'), ('seminari_student', 'Seminary Student')], default='priest', max_length=20),
        ),
    ]
