# Generated by Django 6.0 on 2026-07-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0016_parish_secretary_alter_parish_assistant_vicar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priest',
            name='position',
            field=models.CharField(choices=[('viacar', 'Vicar'), ('retired_priest', 'Retired Priest'), ('student_priest', 'Student Priest')], default='vicar', max_length=20),
        ),
    ]
