# Generated by Django 6.0 on 2026-08-19 09:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0016_alter_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Synod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='synod/')),
                ('description', models.TextField(blank=True, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_numbers', models.JSONField(blank=True, default=list, help_text='Enter multiple phone numbers as a JSON list.')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Synod',
                'verbose_name_plural': 'Synods',
                'ordering': ['name'],
            },
        ),
    ]
