# Generated by Django 6.0 on 2026-08-31 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0017_synod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kalpanafile',
            name='file',
            field=models.FileField(help_text='Upload PDF file only', upload_to='kalpana_files/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
