# Generated by Django 6.0 on 2026-07-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0018_alter_priest_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priest',
            name='position',
            field=models.CharField(choices=[('vicar', 'Vicar'), ('retired_priest', 'Retired Priest'), ('seminari_student', 'Seminary Student')], default='priest', max_length=20),
        ),
    ]
