# Generated by Django 6.0 on 2026-08-31 06:33

import dioceseapp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0018_alter_kalpanafile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kalpanafile',
            name='file',
            field=models.FileField(help_text='Upload PDF file only', upload_to='kalpana_files/%Y/%m/', validators=[dioceseapp.models.validate_pdf_file, django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
