# Generated by Django 6.0 on 2026-08-31 06:47

import dioceseapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0019_alter_kalpanafile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayerbook',
            name='file',
            field=models.FileField(blank=True, help_text='Upload PDF file only', null=True, upload_to='prayer_books/files/', validators=[dioceseapp.models.validate_pdf_file], verbose_name='PDF File'),
        ),
    ]
