# Generated by Django 6.0 on 2026-07-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0020_alter_priest_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priest',
            name='position',
            field=models.CharField(choices=[('priest', 'Priest'), ('retired_priest', 'Retired Priest'), ('seminary_student', 'Seminary Student')], default='priest', max_length=20),
        ),
    ]
