# Generated by Django 6.0 on 2026-07-23 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0021_alter_priest_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parish',
            name='assistant_vicar',
            field=models.ForeignKey(blank=True, limit_choices_to={'position': 'priest'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_vicar_parishes', to='dioceseapp.priest'),
        ),
        migrations.AlterField(
            model_name='parish',
            name='vicar',
            field=models.ForeignKey(blank=True, limit_choices_to={'position': 'priest'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parishes', to='dioceseapp.priest'),
        ),
    ]
