# Generated by Django 6.0 on 2026-07-23 10:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0022_alter_parish_assistant_vicar_alter_parish_vicar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priest',
            name='pastoral_church',
        ),
        migrations.RemoveField(
            model_name='priest',
            name='pastoral_designation',
        ),
        migrations.RemoveField(
            model_name='priest',
            name='pastoral_from_year',
        ),
        migrations.RemoveField(
            model_name='priest',
            name='pastoral_to_year',
        ),
        migrations.AddField(
            model_name='priest',
            name='pastoral_experience',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Pastoral Experience'),
        ),
    ]
