# Generated by Django 6.0 on 2026-09-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dioceseapp', '0023_alter_prayerbook_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayerbook',
            name='file',
            field=models.FileField(blank=True, help_text='Upload PDF file only', null=True, upload_to='prayer_books/files/', verbose_name='PDF File'),
        ),
    ]
